# Generated by Django 5.1.2 on 2024-11-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_goal_socialnetwork_user_age_user_bio_user_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='goals',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='account.goal'),
        ),
    ]
