# Generated by Django 5.1.2 on 2024-11-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_goals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goal',
            new_name='Heshtag',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='goals',
            new_name='heshstags',
        ),
        migrations.AddField(
            model_name='user',
            name='social_networks',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='account.socialnetwork'),
        ),
    ]
