# Generated by Django 5.1.2 on 2024-11-14 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_goal_heshtag_rename_goals_user_heshstags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='heshstags',
            new_name='heshtags',
        ),
    ]
