# Generated by Django 5.1.2 on 2024-10-31 17:28

import django.core.validators
import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvideo',
            name='video',
            field=models.FileField(upload_to='post/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'gif']), post.models.validate_video_size]),
        ),
    ]
