# Generated by Django 5.1.2 on 2024-10-31 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_postvideo_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
