# Generated by Django 5.1.2 on 2024-11-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_postimage_post_alter_postvideo_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hidden',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
